# Use root/example as user/password credentials
version: '3'

services:
  seasstash:
    build: ./
    image: seasx/seasstashphp:latest
    volumes:
    - ./:/data
    - ./docker/docker-php-ext-seaslog.ini:/usr/local/etc/php/conf.d/docker-php-ext-seaslog.ini
    - ./docker/php.ini:/usr/local/etc/php/php.ini
    command: php ./bin/SeasStash start
    ulimits:
      nofile:
       soft: 262144
       hard: 262144
    depends_on:
      - clickhouse
    ports:
      - 6060:80
      - 514:514
      - 5014:5014
    networks:
      - SeasStashPHP
  clickhouse:
      image: yandex/clickhouse-server
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /docker/clickhouse/data:/var/lib/clickhouse/data
        - /docker/clickhouse/metadata:/var/lib/clickhouse/metadata
        - ./docker/config.xml:/etc/clickhouse-server/config.xml
      ports:
        - 8123:8123
        - 9000:9000
        - 9009:9009
      ulimits:
        nofile:
         soft: 262144
         hard: 262144
      networks:
        - SeasStashPHP
  ckweb:
      image: spoonest/clickhouse-tabix-web-client
      environment:
        CH_NAME: default
        CH_HOST: clickhouse:8123
      depends_on:
        - clickhouse
      ports:
        - 8080:80
      volumes:
        - /etc/localtime:/etc/localtime:ro
      networks:
        - SeasStashPHP

  superset:
      image: amancevice/superset
      restart: always
      depends_on:
        - db
        - redis
      ports:
        - 8088:8088
      volumes:
        - ./docker/superset_config.py:/etc/superset/superset_config.py
        - /etc/localtime:/etc/localtime:ro
      networks:
        - SeasStashPHP

  redis:
    image: redis:4.0.11-alpine
    hostname: redis
    volumes:
    - /docker/redis/data:/data
    - /etc/localtime:/etc/localtime:ro
    ports:
    - 6379:6379
    networks:
      - SeasStashPHP

  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - /docker/mysql/data:/var/lib/mysql
    command: --max_connections=512 --explicit_defaults_for_timestamp=1 --sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
              --tmp_table_size=18M --thread_cache_size=8 --query_cache_size=0 --myisam_max_sort_file_size=64G
              --myisam_sort_buffer_size=35M --key_buffer_size=25M --read_buffer_size=64K --read_rnd_buffer_size=256K --sort_buffer_size=256K
              --max_allowed_packet=128M --innodb_flush_log_at_trx_commit=1 --innodb_log_buffer_size=1M
              --innodb_buffer_pool_size=47M --innodb_log_file_size=24M --innodb_thread_concurrency=8 --default-time-zone="+8:00"
    ports:
    - 3306:3306
    networks:
      - SeasStashPHP

networks:
  SeasStashPHP:
    external:
      name: SeasStash